#!mainFile "../genji.opy"
rule "test data":

    A = [vect(2.781, 0, -19.455), vect(-19.495, 0, -19.491), vect(-18.672, 0, 3.661), vect(-19.349, 0, 19.495), vect(17.624, 0, 19.38)]
    TimeRemaining = 261
    H = []
    I = []
    Dao = []
    SHIFT = []
    TQ = []
    EditMode = []
    TQ5 = []
    TQ6 = []
    BounceToggleLock = []
    killballnumber = []
    pinballnumber = []
    LeaderBoardFull = []
    LeaderBoardHuds = []
    LeaderBoardRemake = true
    DashExploitToggle = true
    PortalNames = []
    PortalLoc = []
    PortalDest = []
    PortalOn = false
    CustomPortalStart = []
    CustomPortalEndpoint = []
    CustomPortalCP = []
    CompMode = false
    instructiontext = ["Change in Comp Mode instruction message hud 1", "Change in Comp Mode instruction message hud 2", "Change in Comp Mode instruction message hud 2", "Change in Comp Mode instruction message hud 2"]
    HudStoreEdit = []
    SaveName = []
    SaveCp = []
    SaveEnt = []
    SaveTimer = []
    SaveElapsed = []
    SavePauseTime = []
    SavePauseEnabled = []
    Cachedcredits = ["name here - 作者", "code here - 代码"]
    
    wait(3)
    BanMulti = [2]
    BanCreate = []
    BanDead = []
    BanEmote = []
    BanClimb = []
    BanBhop = []
