rule "testdata":
    A = [vect(10.025, 0, -7.273), vect(3.51, 0, -6.919), vect(-3.654, 0, -7.654)]
    H = []
    I = []
    TQ = []
    EditMode = []
    TQ5 = []
    TQ6 = []
    killballnumber = []
    pinballnumber = []
    Cachedcredits = ["aaaaaaa", "bbbbb"]
    wait(1)
    
    HintCp = [1,2]
    HintText = [
        "Simply get to the next checkpoint by usings your abilities.\n"
        " Also don't touch the ground.",
        "Do a 360 or it won't be cool enough to count"

    ]